name: Go Example Workflow

on:
  schedule:
    - cron: '*/15 * * * 1-6'  # A cada 15 minutos de segunda a sábado
  push:
    branches:
      - main

env:
  FILE_NAME: hello-server

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build for Linux
        run: go build ${{ env.FILE_NAME }}.go

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

      - name: Upload artifact Linux
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: ./hello-server

      - name: Upload artifact Windows
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: ./hello-server.exe

  download-and-run-linux:
    needs: build-go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Linux Artifact
        uses: actions/download-artifact@v3
        with:
          name: linux

      - name: Run Script
        run: source ./run.sh

  download-only-windows:
    needs: build-go
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Windows Artifact
        uses: actions/download-artifact@v3
        with:
          name: windows

